#!/bin/bash

brew install \
    mdcat \
    ghq \
    fzf \
    ripgrep \
    bat \
    fd \
    expect \
    koekeishiya/formulae/yabai \
    koekeishiya/formulae/skhd \
    deno \
    go

if [! -e ~/src ]
then
    # for ghq root
    mkdir ~/src
fi

bash ./ghqinit.sh
