#!/bin/bash

# ghqの管理下ならdotfiles自体をシンボリックリンクで生成する
GHQ_ROOT=~/src
DOTFILE_REPOSITORY=github.com/yCroma/dotfiles
GHQ_DOTFILES_PATH=${GHQ_ROOT}/${DOTFILE_REPOSITORY}

if [[ -e ${GHQ_DOTFILES_PATH} ]]
then
    echo "dotfiles is managed by ghq"
        bash ./unlink
        echo "old links were removed"
    if [ -L ~/dotfiles ]; then
        unlink ~/dotfiles
        echo "dotfiles was unlinked"
    fi
	if [ -e ~/dotfiles ]; then
		rm -rf ~/dotfiles
        echo "old dotfiles was removed"
	fi
    ln -sfv ${GHQ_DOTFILES_PATH} ${HOME}/dotfiles
fi

# PATH ~/dotfiles
DOTFILES=$(ls -a ~/dotfiles | awk '/^\.[a-z]+/')

for DOTFILE in ${DOTFILES[@]}
do
	LINK_PATH=~/${DOTFILE}
	USE_FILE=~/dotfiles/${DOTFILE}

	if [[ ${DOTFILE} =~ (\.swp)$ ]]; then
		continue
	fi

	if [ ${DOTFILE} == ".gitignore_global" ]; then
		ln -sfv ${USE_FILE} ${LINK_PATH}
		git config --global core.excludesfile ~/.gitignore_global
	fi

	if [[ ${DOTFILE} =~ ^(\.git) ]]; then
		continue
	fi

	if [ -e ${LINK_PATH} ]; then
		rm -rf ${LINK_PATH}
	fi
	ln -sfv ${USE_FILE} ${LINK_PATH}
done
