#!/bin/bash

# LTS ubuntu reposiroty
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
sudo apt-get install -y nodejs
# vim reposiroty
sudo add-apt-repository -y ppa:jonathonf/vim
# zsh
sudo apt-get install -y zsh

sudo apt update
sudo apt install -y \
	unzip \
	golang \
    vim \
	tmux \
	fzf \
	bat \
	fd-find \
	ripgrep

# deno
curl -fsSL https://deno.land/x/install/install.sh | sh
deno upgrade --version 1.11.0

# go + ghq
go get github.com/motemen/ghq

if [! -e ~/src ]
then
    # for ghq root
    mkdir ~/src
fi

bash ./ghqinit.sh
