#!/bin/zsh

glog() {
  #is_in_git_repo || return
  git log \
      --date=short \
      --format="%C(auto)%h%d %s (%an) %C(black)%C(bold)%cr" \
      --graph \
      --color=always \
      | \
      fzf \
      --ansi \
      --no-sort \
      --reverse \
      --multi \
      --bind 'ctrl-s:toggle-sort' \
      --header 'Press CTRL-S to toggle sort' \
      --preview-window down:50% \
      --preview 'grep -o "[a-f0-9]\{7,\}" <<< {} | xargs git show --color=always' | grep -o "[a-f0-9]\{7,\}"
}

glog
