#!/bin/zsh

removePath=$(fd --no-ignore --hidden --follow --exclude .git | fzf --height 100% --preview 'FDcheck(){
    if [[ -f $1 ]]; then
        bat --color=always --style=changes,numbers $1
    else
        fd . $1 --color=always
    fi
}; FDcheck {}' --preview-window down:60%)

if [ -n "$removePath" ]
then
    echo "remove $removePath"
    rm -rf $removePath
fi
