#!/bin/zsh

removePath=$(fd --hidden --follow --exclude .git | fzf --height 100% --preview 'bat --color=always --style=numbers,changes --line-range=:100 {}' --preview-window down:80%)

if [ -n "$removePath" ]
then
    echo "remove $removePath"
    rm -rf $removePath
fi
