#!/bin/zsh

gadd() {
    local selected
    selected=$(unbuffer git status -s | \
        fzf -m --ansi \
            --preview-window down:50% \
            --preview "echo {} | awk '{print \$2}' | xargs git diff --color=always" | \
        awk '{print $2}')
    if [[ -n "$selected" ]]; then
        selected=$(tr '\n' ' ' <<< "$selected")
        git add $(echo $selected)
        echo "added: $selected"
        git commit -v
        echo 'commited!'
    fi
}

gadd
