#!/bin/zsh

gadd() {
    local selected
    selected=$(unbuffer git status -s | \
        fzf -m --ansi \
            --preview-window down:50% \
            --preview "echo {} | awk '{print \$2}' | xargs git diff --color" | \
        awk '{print $2}')
    if [[ -n "$selected" ]]; then
        # selected=$(tr '\n' '\ ' <<< "$selected" | sed 's/\s*$//')
        selected=$(tr '\n' ' ' <<< "$selected")
        echo "added: $selected"
        # commiting
        read str\?"commit message> "
        # 実際にcommit messageを決めるときにaddしたいから
        # stagingはif文の内部で行う
        if [[ -n "$str" ]]; then
            # 文字列への変換がうまくいかなかったので下のようにした
            git add $(echo $selected)
            git commit -m $str
            echo 'commited!'
            #printf '%sコミットされました' "$str"
        else
            echo '空のコミットでよいですか？(y/N): '
            if read -q; then
                echo '空のコミット'
            else
                echo 'aborted.'
            fi
        fi
    fi
}

gadd
