#!/bin/zsh

# 上位互換のgaddを作成したため、gdifは利用しない
gdif() {
    local selected
    selected=$(unbuffer git status -s | \
        fzf -m --ansi \
            --preview-window down:50% \
            --preview "echo {} | awk '{print \$2}' | xargs bat --color=always --style=changes,numbers" | \
        awk '{print $2}')
    if [[ -n "$selected" ]]; then
        selected=$(tr '\n' ' ' <<< "$selected")
        vim $(echo $selected)
    fi
}

gdif
