#!/bin/zsh

destination_dir="$(ghq root)/$(ghq list | fzf --layout=reverse --height 40% --border --preview "git --git-dir $(ghq root)/{}/.git log --date=short --pretty=format:'-%C(yellow)%d%Creset %s %Cgreen(%cd) %C(bold blue)<%an>%Creset' --color")"

repo_name=${destination_dir##*/}

if [ -n "$destination_dir" ]; then
    echo $destination_dir

    if [ -z ${TMUX}]
    then
        echo "dive into tmux"
        tmux new -A -s $repo_name -c $destination_dir
    else
        echo "in tmux now"
        echo $destination_dir
        echo ${destination_dir##*/}
        tmux new-session -s $repo_name -d -c $destination_dir
        tmux switch-client -t $repo_name
        cd $destination_dir
    fi
fi
